restore config at pre-reboot, keep all file, use ext4
move restore config to pre-reboot avoid small boot partation
keep all file with -o mode, aka preserve all changed files in /
use ext4 by default instead f2fs

diff --git a/package/base-files/files/sbin/sysupgrade b/package/base-files/files/sbin/sysupgrade
--- a/package/base-files/files/sbin/sysupgrade
+++ b/package/base-files/files/sbin/sysupgrade
@@ -71,8 +71,7 @@ upgrade-option:
 	-f <config>  restore configuration from .tar.gz (file or url)
 	-i           interactive mode
 	-c           attempt to preserve all changed files in /etc/
-	-o           attempt to preserve all changed files in /, except those
-	             from packages but including changed confs.
+	-o           attempt to preserve all changed files in /
 	-u           skip from backup files that are equal to those in /rom
 	-n           do not save configuration over reflash
 	-p           do not attempt to restore the partition table after flash.
@@ -138,7 +137,7 @@ list_changed_conffiles() {
 list_static_conffiles() {
 	local filter=$1
 
-	find $(sed -ne '/^[[:space:]]*$/d; /^#/d; p' \
+	find $(sed -ne '/^[[:space:]]*$/d; /^#/d; /^\/$/d; p' \
 		/etc/sysupgrade.conf /lib/upgrade/keep.d/* 2>/dev/null) \
 		\( -type f -o -type l \) $filter 2>/dev/null
 }
@@ -154,39 +153,6 @@ add_conffiles() {
 add_overlayfiles() {
 	local file="$1"
 
-	local packagesfiles=$1.packagesfiles
-	touch "$packagesfiles"
-
-	if [ "$SAVE_OVERLAY_PATH" = / ]; then
-		local conffiles=$1.conffiles
-		local keepfiles=$1.keepfiles
-
-		list_conffiles | cut -f2 -d ' ' | sort -u > "$conffiles"
-
-		# backup files from /etc/sysupgrade.conf and /lib/upgrade/keep.d, but
-		# ignore those aready controlled by opkg conffiles
-		list_static_conffiles | sort -u |
-			grep -h -v -x -F -f $conffiles > "$keepfiles"
-
-		# backup conffiles, but only those changed if '-u'
-		[ $SKIP_UNCHANGED = 1 ] &&
-			list_changed_conffiles | sort -u > "$conffiles"
-
-		# do not backup files from packages, except those listed
-		# in conffiles and keep.d
-		{
-			find /usr/lib/opkg/info -type f -name "*.list" -exec cat {} \;
-			find /usr/lib/opkg/info -type f -name "*.control" -exec sed \
-				-ne '/^Alternatives/{s/^Alternatives: //;s/, /\n/g;p}' {} \; |
-				cut -f2 -d:
-		} |  grep -v -x -F -f $conffiles |
-		     grep -v -x -F -f $keepfiles | sort -u > "$packagesfiles"
-		rm -f "$keepfiles" "$conffiles"
-	fi
-
-	# busybox grep bug when file is empty
-	[ -s "$packagesfiles" ] || echo > $packagesfiles
-
 	( cd /overlay/upper/; find .$SAVE_OVERLAY_PATH \( -type f -o -type l \) $find_filter | sed \
 		-e 's,^\.,,' \
 		-e '\,^/etc/board.json$,d' \
@@ -194,9 +160,7 @@ add_overlayfiles() {
 		-e '\,^/etc/urandom.seed$,d' \
 		-e "\,^$INSTALLED_PACKAGES$,d" \
 		-e '\,^/usr/lib/opkg/.*,d' \
-	) | grep -v -x -F -f $packagesfiles > "$file"
-
-	rm -f "$packagesfiles"
+	) > "$file"
 
 	return 0
 }
@@ -232,7 +196,7 @@ do_save_conffiles() {
 		return 0
 	}
 	run_hooks "$CONFFILES" $sysupgrade_init_conffiles
-	ask_bool 0 "Edit config file list" && vi "$CONFFILES"
+	ask_bool 0 "Edit config file list" && vim "$CONFFILES"
 
 	if [ "$SAVE_INSTALLED_PKGS" -eq 1 ]; then
 		echo "${INSTALLED_PACKAGES}" >> "$CONFFILES"
@@ -262,6 +226,12 @@ do_save_conffiles() {
 		echo "Failed to create the configuration backup."
 		rm -f "$conf_tar"
 		exit 1
+	fi
+	find /overlay/upper -type c -exec tar -rvf /tmp/sysupgrade.tar {} \;
+	local err=$?
+	if [ "$err" -ne 0 ]; then
+		echo "Failed to create the configuration backup."
+		rm -f /tmp/sysupgrade.tar
 	fi
 
 	[ "$UMOUNT_ETCBACKUP_DIR" -eq 1 ] && {
